# Lista 8

# Exercicio 1

Temos o algoritmo:

1. $x_n = b_n/a{nn}$
2. para $k$ de $n-1$ até $1$ faça
3.    $\hspace{1.5cm}x_k = (b_k - \sum_{j = k+1}^n a_{kj}x_j)/a_{kk}$
4. end
5. return $x$

Para a análise, vamos desconsiderar a linha 1 que é executada apenas uma vez. Dentro do laço todos os passos são executados $n$ vezes. Na linha 3 temos uma divisão (então temos $n$ divisões no total) e o somatório de uma multiplicação, que é dependente de $k$, temos a seguinte tabela para as multiplicações desse somatório: 


$k\hspace{2cm}$        somatório inicia em $k+1\hspace{2cm}$ e vai até $n\hspace{3cm} Temos:$     

$
n-1\hspace{3cm} n\hspace{5cm}n\hspace{3cm} 1 \text{ multiplicação}\\
n-2\hspace{3cm} n-1\hspace{4.3cm}n\hspace{3cm} 2 \text{ multiplicações}\\
n-3\hspace{3cm} n-2\hspace{4.3cm}n\hspace{3cm} 3\text{ multiplicações}\\
.\\
.\\
.\\
1\hspace{3.8cm} 2\hspace{5cm}n\hspace{3cm} n-1 \text{ multiplicações}\\
$

Então temos o seguinte: $1 + 2 + 3 + ... + n-1$ multiplicações
que podemos resolver da seguinte maneira:

$((n-1)+1)(n-1)/2$

Logo temos:

$\frac{n²-n}{2}$ multiplições na linha 3

Considerando apenas o maior termo assintoticamente temos que o algoritmo é da ordem de $O\left(\frac{n²-n}{2}\right) = O(n²)$

# Exercicio 2

In [167]:
import numpy as np

In [168]:
n = 4
A = [[1, 3, 7, 8],[1, -1, 0, 1],[7, 10, 1, 9],[-1, 0, 1, 1]]

In [169]:
p = []
for i in range(1, n+1):
    p.append(i)
p

[1, 2, 3, 4]

In [170]:
for i in range(0, n-1):
    maxindice = i
    maxelemento = A[i][i]
    for j in range(i+1,n):
        if A[j][i] > maxelemento: 
            maxindice = j
            maxelemento = A[j][i]

    
    #trocando linhas na matriz
    if A[i][i] != maxelemento:
        aux = A[i]
        A[i] = A[maxindice]
        A[maxindice] = aux
        
        #trocando linhas na matriz de permutacao
        aux2 = p[i]
        p[i] = p[maxindice]
        p[maxindice] = aux2

    #anulando elementos abaixo do pivo
    for j in range(i+1, n):
        m = A[j][i]/A[i][i]
        for s in range(i, n):
            A[j][s] = A[j][s]-(m*A[i][s])
        A[j][i] = m
        
print('Matriz A = ',A)
print('Vetor P = ',p)

P = np.zeros((4,4),dtype = np.int)

for i in range(0,n):
    for j in range(0,n):
        if p[i] == j+1:
            P[i][j] = 1
print('Matriz P = ', P)

Matriz A =  [[7, 10, 1, 9], [0.14285714285714285, 1.5714285714285716, 6.857142857142857, 6.714285714285714], [0.14285714285714285, -1.5454545454545452, 10.454545454545453, 10.09090909090909], [-0.14285714285714285, 0.9090909090909088, -0.48695652173913023, 1.0956521739130425]]
Vetor P =  [3, 1, 2, 4]
Matriz P =  [[0 0 1 0]
 [1 0 0 0]
 [0 1 0 0]
 [0 0 0 1]]


In [171]:
L =[[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]]
U =[[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]]
for i in range(0, n):
    for j in range(0, n):
        if i == j:
            L[i][j] = 1
            U[i][j] = A[i][j]
        if i > j:
            L[i][j] = A[i][j]
        if j > i:
            U[i][j] = A[i][j]
print('Matiz L =',L)
print('Matriz U =',U)

Matiz L = [[1, 0, 0, 0], [0.14285714285714285, 1, 0, 0], [0.14285714285714285, -1.5454545454545452, 1, 0], [-0.14285714285714285, 0.9090909090909088, -0.48695652173913023, 1]]
Matriz U = [[7, 10, 1, 9], [0, 1.5714285714285716, 6.857142857142857, 6.714285714285714], [0, 0, 10.454545454545453, 10.09090909090909], [0, 0, 0, 1.0956521739130425]]


# Aqui Verificamos que PA = LU:

In [178]:
PA = np.zeros((4,4),dtype = np.float)
LU = np.zeros((4,4),dtype = np.float)

Aoriginal = [[1, 3, 7, 8],[1, -1, 0, 1],[7, 10, 1, 9],[-1, 0, 1, 1]]

for i in range(0,n):
    for j in range(0,n):
         for k in range(0,n):
                PA[i][j] += P[i][k] * Aoriginal[k][j]

for i in range(0,n):
    for j in range(0,n):
         for k in range(0,n):
                LU[i][j] += L[i][k] * U[k][j]
                

print('Matriz PA = ',PA,'\n\nMatriz LU = ', LU)

Matriz PA =  [[ 7. 10.  1.  9.]
 [ 1.  3.  7.  8.]
 [ 1. -1.  0.  1.]
 [-1.  0.  1.  1.]] 

Matriz LU =  [[ 7. 10.  1.  9.]
 [ 1.  3.  7.  8.]
 [ 1. -1.  0.  1.]
 [-1.  0.  1.  1.]]


In [ ]:
b = []
for i in range(0,n):
    b.append(1)
print('vetor b = ', b)

$LUx = Pb$

In [179]:
LU * x = P*b

SyntaxError: can't assign to operator (<ipython-input-179-cf4fd8712970>, line 1)

### Verificacao usando funcao pronta:

In [159]:
np.linalg.solve(A, b)

array([-0.67705922,  0.12592051, -0.3998505 ,  0.54222889])