# Lista 10

# Exercicio 1

In [64]:
import numpy as np
import math

A = np.array([[1,0,4],[1,3,1],[2,4,-1]])

print(A)

[[ 1  0  4]
 [ 1  3  1]
 [ 2  4 -1]]


### Temos como Polinomio caracteristico:
$(1-\lambda)(3-\lambda)(-1-\lambda) + 16 -4(3-\lambda)2 - 4(1-\lambda)$

$-15 + 13\lambda + 3 \lambda^2 - \lambda^3$

In [65]:
z = [-15,13,3,-1]
ava1 = np.polynomial.polynomial.polyroots(z)
ava1

array([-3.,  1.,  5.])

In [66]:
ava2, ave = np.linalg.eig(A)

In [67]:
ava2

array([ 5.,  1., -3.])

### Temos que das duas formas chegamos aos mesmos autovalores

## Construindo as matrizes caracteristicas para cada autovalor:

In [68]:
A1 = np.array([[1,0,4],[1,3,1],[2,4,-1]])

for i in range(0,3):
    for j in range(0,3):
        if i==j:
            A1[i][j] = A1[i][j] - np.round(ava2[0])

A2 = np.array([[1,0,4],[1,3,1],[2,4,-1]])

for i in range(0,3):
    for j in range(0,3):
        if i==j:
            A2[i][j] = A2[i][j] - np.round(ava2[1])

A3 = np.array([[1,0,4],[1,3,1],[2,4,-1]])

for i in range(0,3):
    for j in range(0,3):
        if i==j:
            A3[i][j] = A3[i][j] - np.round(ava2[2])
            
A2[0] = A2[2]
A2[2] = [0,0,4]

print('A1 = \n', A1, '\nA2 = \n', A2, '\nA3 = \n', A3)

A1 = 
 [[-4  0  4]
 [ 1 -2  1]
 [ 2  4 -6]] 
A2 = 
 [[ 2  4 -2]
 [ 1  2  1]
 [ 0  0  4]] 
A3 = 
 [[4 0 4]
 [1 6 1]
 [2 4 2]]


### Escalonando Matrix $A_1$

In [69]:
for s in range(0,2):
    
    for i in range(s+1,3):
        soma = []
        
        b = A1[i][s]/A1[s][s]

        for j in range(0,3):
            soma.append(A1[i][j]-b*A1[s][j])

        
        A1[i] = soma

print(A1)

[[-4  0  4]
 [ 0 -2  2]
 [ 0  0  0]]


### Assim sabemos que temos $dim(N(A_1)) = 1$ e fica facil ver que $v = (1,1,1)^t \in N(A_1)$

### Escalonando Matrix $A_2$

In [70]:
for s in range(0,2):
    
    for i in range(s+1,3):
        
        if A2[s][s] != 0:
            soma = [] 
            b = A2[i][s]/A2[s][s]

            for j in range(0,3):
                soma.append(A2[i][j]-b*A2[s][j])

        
            A2[i] = soma

print(A2)

[[ 2  4 -2]
 [ 0  0  2]
 [ 0  0  4]]


### Assim sabemos que temos $dim(N(A_2)) = 1$ (linha 2 e 3 sao LD) e fica facil ver que $v = (-2,1,0)^t \in N(A_2)$

### Escalonando Matrix $A_3$

In [71]:
for s in range(0,2):
    
    for i in range(s+1,3):
        
        if A3[s][s] != 0:
            soma = [] 
            b = A3[i][s]/A3[s][s]

            for j in range(0,3):
                soma.append(A3[i][j]-b*A3[s][j])

        
            A3[i] = soma

print(A3)

[[4 0 4]
 [0 6 0]
 [0 0 0]]


### Assim sabemos que temos $dim(N(A_3)) = 1$e fica facil ver que $v = (-1,0,1)^t \in N(A_3)$

## Temos entao como autovetores:

In [72]:
v1 = [1,1,1]
v2 = [-2,1,0]
v3 = [-1,0,1]

# Verificando que $Av=λv$ para cada par de autovalor e autovetor obtido:

In [73]:
print(np.dot(A, v1), '=', np.dot(ava2[0], v1))

[5 5 5] = [5. 5. 5.]


In [74]:
print(np.dot(A, v2), '=', np.dot(ava2[1], v2))

[-2  1  0] = [-2.  1.  0.]


In [75]:
print(np.dot(A, v3), '=', np.dot(ava2[2], v3))

[ 3  0 -3] = [ 3.  0. -3.]


## Podemos diagonalizar A, pois $A \in \mathbb{R}^{nxn}$ e possui $n$ autovetores L.I.

## Encontrando fatores S e Λ

In [76]:
S = np.array([[1,-2,-1],
     [1, 1, 0],
     [1, 0, 1]])

Λ = np.zeros((3,3))

for i in range(0, 3):
    for j in range(0, 3):
        if i == j:
            Λ[i][j] = ava2[i]
print('S = \n',S,'\n Λ =\n', Λ)

S = 
 [[ 1 -2 -1]
 [ 1  1  0]
 [ 1  0  1]] 
 Λ =
 [[ 5.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0. -3.]]


In [77]:
Sinv = np.linalg.inv(S)

In [78]:
print(A, '\n = \n', np.dot(np.dot(S, Λ), Sinv))

[[ 1  0  4]
 [ 1  3  1]
 [ 2  4 -1]] 
 = 
 [[ 1.00000000e+00  1.55431223e-15  4.00000000e+00]
 [ 1.00000000e+00  3.00000000e+00  1.00000000e+00]
 [ 2.00000000e+00  4.00000000e+00 -1.00000000e+00]]


# Assim verificamos que $A=SΛS^{−1}$

# Exercicio 2

In [79]:
B = np.array([[4,0,-2],
    [0,2,0],
    [-2,0,4]])
B

array([[ 4,  0, -2],
       [ 0,  2,  0],
       [-2,  0,  4]])

### Temos como Polinomio caracteristico:
$(4-\lambda)(2 -\lambda)(4-\lambda) - 4(2-\lambda)$

$40 - 36\lambda + 10\lambda^2 - \lambda^3$

In [80]:
z = [24,-28,10,-1]

ava = np.round(np.polynomial.polynomial.polyroots(z))
ava

array([2., 2., 6.])

In [81]:
ava2, ave = np.linalg.eig(B)
ava2

array([6., 2., 2.])

### Temos que das duas formas chegamos aos mesmos autovalores

## Construindo as matrizes caracteristicas para cada autovalor:

In [82]:
B1 = np.array([[4,0,-2],[0,2,0],[-2,0,4]])

for i in range(0,3):
    for j in range(0,3):
        if i==j:
            B1[i][j] = B1[i][j] - np.round(ava2[0])

B2 = np.array([[4,0,-2],[0,2,0],[-2,0,4]])

for i in range(0,3):
    for j in range(0,3):
        if i==j:
            B2[i][j] = B2[i][j] - np.round(ava2[1])

B3 = np.array([[4,0,-2],[0,2,0],[-2,0,4]])

for i in range(0,3):
    for j in range(0,3):
        if i==j:
            B3[i][j] = B3[i][j] - np.round(ava2[2])

print('B1 = \n', B1, '\nB2 = \n', B2, '\nB3 = \n', B3)

B1 = 
 [[-2  0 -2]
 [ 0 -4  0]
 [-2  0 -2]] 
B2 = 
 [[ 2  0 -2]
 [ 0  0  0]
 [-2  0  2]] 
B3 = 
 [[ 2  0 -2]
 [ 0  0  0]
 [-2  0  2]]


### Escalonando Matrix $B_1$

In [83]:
for s in range(0,2):
    
    for i in range(s+1,3):
        
        if B1[s][s] != 0:
            soma = [] 
            b = B1[i][s]/B1[s][s]

            for j in range(0,3):
                soma.append(B1[i][j]-b*B1[s][j])

        
            B1[i] = soma

print(B1)

[[-2  0 -2]
 [ 0 -4  0]
 [ 0  0  0]]


### Assim sabemos que temos $dim(N(B_1)) = 1$ e fica facil ver que $v = (-1,0,1)^t \in N(B_1)$

### Escalonando Matrix $B_2$

In [84]:
for s in range(0,2):
    
    for i in range(s+1,3):
        
        if B2[s][s] != 0:
            soma = [] 
            b = B2[i][s]/B2[s][s]

            for j in range(0,3):
                soma.append(B2[i][j]-b*B2[s][j])

        
            B2[i] = soma

print(B2)

[[ 2  0 -2]
 [ 0  0  0]
 [ 0  0  0]]


### Assim sabemos que temos $dim(N(B_2)) = 2$ e fica facil ver que $v_1 = (0,1,0)^t$ e $v_2 = (1,0,1)^t \colon v_1, v_2 \in N(B_2)$

### Como temos $2$ autovalores iguais, na matriz $B_3$ temos os mesmos autovetores de $B_2$

## Temos entao como autovetores:

In [85]:
v1 = [-1,0,1]
v2 = [0,1,0]
v3 = [1,0,1]

# Verificando que $Bv=λv$ para cada par de autovalor e autovetor obtido:

In [86]:
print(np.dot(B, v1), '=', np.dot(ava2[0], v1))

[-6  0  6] = [-6.  0.  6.]


In [87]:
print(np.dot(B, v2), '=', np.dot(ava2[1], v2))

[0 2 0] = [0. 2. 0.]


In [88]:
print(np.dot(B, v3), '=', np.dot(ava2[2], v3))

[2 0 2] = [2. 0. 2.]


## Encontrando $Q$:

In [89]:
q1 = np.divide(v1, np.linalg.norm(v1))
q2 = np.divide(v2, np.linalg.norm(v2))

v3l = v3 - np.dot(np.dot(q2,v3),q2)
q3 = np.divide(v3l, np.linalg.norm(v3l))

Q = np.array([[q1[0],q2[0],q3[0]],[q1[1],q2[1],q3[1]],[q1[2],q2[2],q3[2]]])
Q

array([[-0.70710678,  0.        ,  0.70710678],
       [ 0.        ,  1.        ,  0.        ],
       [ 0.70710678,  0.        ,  0.70710678]])

## Encontrando Λ:

In [90]:
Λ = np.zeros((3,3))

for i in range(0, 3):
    for j in range(0, 3):
        if i == j:
            Λ[i][j] = ava2[i]
            
print('Λ =\n', Λ)

Λ =
 [[6. 0. 0.]
 [0. 2. 0.]
 [0. 0. 2.]]


# Agora podemos verificar $B=QΛQ^t$

In [91]:
Qinv = np.linalg.inv(Q)

print('B = \n', B, '\n = \n', np.dot(np.dot(Q,Λ),Qinv))

B = 
 [[ 4  0 -2]
 [ 0  2  0]
 [-2  0  4]] 
 = 
 [[ 4.  0. -2.]
 [ 0.  2.  0.]
 [-2.  0.  4.]]


# Exercicio 3

In [92]:
C = np.array([[1,4],[2,8]])
C

array([[1, 4],
       [2, 8]])

In [93]:
ava3,ave3 = np.linalg.eig(np.dot(C,C.T))
ava4,ave4 = np.linalg.eig(np.dot(C.T,C))

print('For CC^t:\n', ava3,'\n',ave3,'\nFor C^tC: \n',ava4,'\n',ave4)

print('CC^t = \n', np.dot(C,C.T), '\nC^tC = \n', np.dot(C.T,C))

For CC^t:
 [ 0. 85.] 
 [[-0.89442719 -0.4472136 ]
 [ 0.4472136  -0.89442719]] 
For C^tC: 
 [ 0. 85.] 
 [[-0.9701425  -0.24253563]
 [ 0.24253563 -0.9701425 ]]
CC^t = 
 [[17 34]
 [34 68]] 
C^tC = 
 [[ 5 20]
 [20 80]]


## Definindo Σ

In [165]:
Σ = np.zeros((2,2))
Σ[0][0] = np.sqrt(ava3[0])
Σ[1][1] = np.sqrt(ava3[1])

# Como podemos ver sao todos ortogonais os autovetores:

In [166]:
np.dot(ave3[0], ave3[1]), np.dot(ave4[0], ave4[1])

(0.0, 0.0)

In [167]:
U = ave3
V = ave4

In [175]:

print(U,'\n\n',Σ,'\n\n',V.T, '\n\n')

U1,s,Vh1 = np.linalg.svd(C, full_matrices=True)
S1 = np.diag(s)
print(U1,'\n\n', S1,'\n\n', Vh1)

[[-0.89442719 -0.4472136 ]
 [ 0.4472136  -0.89442719]] 

 [[0.         0.        ]
 [0.         9.21954446]] 

 [[-0.9701425   0.24253563]
 [-0.24253563 -0.9701425 ]] 


[[-0.4472136  -0.89442719]
 [-0.89442719  0.4472136 ]] 

 [[9.21954446e+00 0.00000000e+00]
 [0.00000000e+00 2.15414908e-16]] 

 [[-0.24253563 -0.9701425 ]
 [-0.9701425   0.24253563]]


# Verificando que $C=UΣV^t$

In [97]:
print(C, "\n = \n", np.dot(np.dot(U,Σ),V.T))

[[1 4]
 [2 8]] 
 = 
 [[1. 4.]
 [2. 8.]]


# $C(C), N(C), C(C^t) e N(C^t)$:

In [98]:
CC = [1,2]
NC = [-4,1]
CCt = [1,4]
NCt = [-2,1]
print('C(C) = \n', CC, '\nN(C) = \n', NC, '\nC(Ct) = \n', CCt, '\nN(Ct) = \n', NCt) 

C(C) = 
 [1, 2] 
N(C) = 
 [-4, 1] 
C(Ct) = 
 [1, 4] 
N(Ct) = 
 [-2, 1]


# Exercicio 4

In [129]:
E = np.array([[1,2,3,4],[3,1,0,-1]])
E

array([[ 1,  2,  3,  4],
       [ 3,  1,  0, -1]])

In [187]:
U,s,Vh = np.linalg.svd(E, full_matrices=True)
S = np.diag(s)

print(U, '\n\n',S,'\n\n', Vh)

[[-0.99862542 -0.05241444]
 [-0.05241444  0.99862542]] 

 [[5.48201483 0.        ]
 [0.         3.30870268]] 

 [[-0.21084743 -0.37388904 -0.54649182 -0.7190946 ]
 [ 0.88961206  0.27013504 -0.04752416 -0.36518337]
 [-0.31273004  0.34855329  0.65805694 -0.58963684]
 [-0.25755322  0.81593177 -0.51579959  0.04327211]]


In [188]:
Sinv = np.diag(1/s)
Epseudoinv = np.dot(np.dot(Vh.T, Sinv), U.T)

ValueError: shapes (4,4) and (2,2) not aligned: 4 (dim 1) != 2 (dim 0)

In [189]:
#A=U Σ Vt
#A†=V Σ† Ut
print(Vh.T, '\n\n',Sinv,'\n\n', U.T)

[[-0.21084743  0.88961206 -0.31273004 -0.25755322]
 [-0.37388904  0.27013504  0.34855329  0.81593177]
 [-0.54649182 -0.04752416  0.65805694 -0.51579959]
 [-0.7190946  -0.36518337 -0.58963684  0.04327211]] 

 [[0.18241468 0.        ]
 [0.         0.30223326]] 

 [[-0.99862542 -0.05241444]
 [-0.05241444  0.99862542]]
